Repository johanhelsing/matchbox, pull requests merged in 2022-10, with the labels that each got.

#40 Upgrade version of webrtc dependency
  Cargo.lock
  matchbox_socket/Cargo.toml
  matchbox_socket/src/webrtc_socket/native/message_loop.rs
Labels: bug

#37 Add ice auth support
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/native/message_loop.rs
  matchbox_socket/src/webrtc_socket/wasm/message_loop.rs
Labels: enhancement

#43 docs: Rustdocs for everything!
  README.md
  matchbox_socket/src/ggrs_socket.rs
  matchbox_socket/src/lib.rs
  matchbox_socket/src/webrtc_socket/mod.rs
Labels: documentation
