Repository johanhelsing/matchbox, pull requests merged in 2023-11, with the labels that each got.

#369 ci: Explain why toml linting fails
  .github/workflows/lint-toml.yml
Labels: ci

#371 chore: cargo update
  Cargo.lock
Labels: dependencies

#362 Add examples for `bevy_matchbox`
  bevy_matchbox/Cargo.toml
  bevy_matchbox/examples/hello.rs
  bevy_matchbox/examples/hello_host.rs
  bevy_matchbox/examples/hello_signaling.rs
Labels: documentation

#373 Make `WebRtcSocket::players()` available for `MultipleChannels` sockets
  matchbox_socket/src/ggrs_socket.rs
Labels: enhancement

#378 dependabot: Group minor and patch level PRs
  .github/dependabot.yml
Labels: ci

#377 ci: Don't run twice on pushes to PR branches
  .github/workflows/code.yml
  .github/workflows/lint-toml.yml
  .github/workflows/markdown-lint.yml
Labels: ci
