Repository johanhelsing/matchbox, pull requests merged in 2023-03, with the labels that each got.

#121 Change default to only use 2 stun servers
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: bug

#117 Unify connections and disconnections API, detect p2p disconnections
  matchbox_demo/src/args.rs
  matchbox_demo/src/main.rs
  matchbox_simple_demo/src/main.rs
  matchbox_socket/src/ggrs_socket.rs
  matchbox_socket/src/lib.rs
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/native.rs
  matchbox_socket/src/webrtc_socket/socket.rs
  matchbox_socket/src/webrtc_socket/wasm.rs
Labels: enhancement

#126 feat: publicize more types
  matchbox_socket/src/lib.rs
  matchbox_socket/src/webrtc_socket/messages.rs
  matchbox_socket/src/webrtc_socket/mod.rs
Labels: enhancement

#132 add update_peers usage to bevy_ggrs example
  examples/bevy_ggrs/src/main.rs
Labels: documentation

#139 Remove `uuid` dependency
  Cargo.lock
  matchbox_socket/Cargo.toml
Labels: enhancement

#140 Don't require `&mut self` for `WebRtcSocket::id`, `players`
  Cargo.lock
  examples/bevy_ggrs/src/main.rs
  matchbox_socket/Cargo.toml
  matchbox_socket/src/ggrs_socket.rs
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: enhancement

#141 Improve logging and code clarity
  matchbox_socket/src/webrtc_socket/native.rs
  matchbox_socket/src/webrtc_socket/socket.rs
  matchbox_socket/src/webrtc_socket/wasm.rs
Labels: enhancement

#149 docs: Link to example folders, not READMEs
  README.md
Labels: documentation

#150 Fix panic on receive after socket future is dropped
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: bug

#151 Make `PeerId` a `Uuid` newtype
  Cargo.lock
  examples/bevy_ggrs/src/box_game.rs
  matchbox_protocol/Cargo.toml
  matchbox_protocol/src/lib.rs
  matchbox_server/src/signaling.rs
  matchbox_socket/Cargo.toml
  matchbox_socket/src/ggrs_socket.rs
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/native.rs
  matchbox_socket/src/webrtc_socket/signal_peer.rs
  matchbox_socket/src/webrtc_socket/socket.rs
  matchbox_socket/src/webrtc_socket/wasm.rs
Labels: enhancement

#156 Fix native crash when connecting to wasm, async blocks
  matchbox_socket/src/webrtc_socket/native.rs
Labels: bug

#159 Remove `UnknownPeerId` error
  examples/bevy_ggrs/src/main.rs
  matchbox_protocol/src/lib.rs
  matchbox_socket/src/ggrs_socket.rs
Labels: enhancement

#161 Update/remove deps
  Cargo.lock
  examples/bevy_ggrs/Cargo.toml
  examples/simple/Cargo.toml
  matchbox_protocol/Cargo.toml
  matchbox_socket/Cargo.toml
Labels: enhancement

#160 Provide abstraction for a channel
  examples/bevy_ggrs/src/main.rs
  matchbox_socket/src/ggrs_socket.rs
  matchbox_socket/src/lib.rs
  matchbox_socket/src/webrtc_socket/error.rs
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: enhancement

#157 Add a Bevy plugin
  Cargo.lock
  Cargo.toml
  bevy_matchbox/Cargo.toml
  bevy_matchbox/README.md
  bevy_matchbox/src/lib.rs
  examples/bevy_ggrs/Cargo.toml
  examples/bevy_ggrs/src/main.rs
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: enhancement

#166 Add `signaling_keep_alive_interval` to socket builder
  matchbox_socket/src/webrtc_socket/mod.rs
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: enhancement

#181 Make `close_socket` command extension usable
  bevy_matchbox/src/lib.rs
  matchbox_socket/src/webrtc_socket/socket.rs
Labels: documentation, enhancement

#186 Add `ggrs` feature to `bevy_matchbox`
  bevy_matchbox/Cargo.toml
Labels: enhancement

#180 Make tests pass on windows
  matchbox_server/src/signaling.rs
  matchbox_signaling/tests/client_server.rs
  matchbox_signaling/tests/full_mesh.rs
Labels: bug

#169 Docs updates ahead of 0.6
  README.md
  images/connection.excalidraw.svg
  images/matchbox_logo.png
Labels: documentation
