Repository johanhelsing/matchbox, pull requests merged in 2023-04, with the labels that each got.

#199 Make `GetChannelError` public
  matchbox_socket/src/lib.rs
  matchbox_socket/src/webrtc_socket/error.rs
Labels: enhancement

#204 Fix panic when signal is received after handshake was completed
  matchbox_socket/src/webrtc_socket/mod.rs
Labels: bug, regression

#206 Add missing `ggrs/wasm-bindgen` dependency for `ggrs` feature
  matchbox_socket/Cargo.toml
Labels: bug, wasm

#208 Update gh checkout action to v3
  .github/workflows/code.yml
  .github/workflows/lint-toml.yml
Labels: ci

#213 fix: ci server image push
  .github/workflows/code.yml
Labels: ci

#209 ci: Switch to dtolnay/rust-toolchain
  .github/workflows/code.yml
Labels: ci
