Repository johanhelsing/matchbox, pull requests merged in 2024-03, with the labels that each got.

#424 Upgrade to bevy 0.13
  Cargo.lock
  README.md
  bevy_matchbox/Cargo.toml
  examples/bevy_ggrs/Cargo.toml
  examples/bevy_ggrs/src/box_game.rs
  examples/bevy_ggrs/src/main.rs
Labels: enhancement

#432 chore: cargo update
  Cargo.lock
Labels: dependencies

#433 chore: update tungstenite deps
  Cargo.lock
  matchbox_server/Cargo.toml
  matchbox_signaling/Cargo.toml
  matchbox_socket/Cargo.toml
Labels: dependencies

#443 Fix new warnings in rust 1.77
  bevy_matchbox/src/socket.rs
Labels: bug, ci

#438 Remove serde-serialize feature
  Cargo.lock
  matchbox_socket/Cargo.toml
Labels: bug

#444 Disable dependabot for cargo
  .github/dependabot.yml
Labels: ci

#445 ci: Run clippy with signaling feature enabled
  .github/workflows/code.yml
  bevy_matchbox/src/signaling.rs
Labels: ci
